'use client';
import { useEffect, useState } from 'react';
import { adminApi } from '@/app/admin/admin-api';
import { useRouter } from 'next/navigation';
import SeoTab from '@/components/seo/SeoTab';

export default function BlogEditor({ id }: { id?: string }) {
  const isEditing = !!id; const router = useRouter();
  const [form, setForm] = useState<any>({ title:'', slug:'', excerpt:'', content:'', cover_image:'', category:'', tags:[], status:'draft', author_name:'' });
  const [tagInput, setTagInput] = useState(''); const [categories, setCategories] = useState<any[]>([]);
  useEffect(() => { adminApi.list<any>('BlogCategory').then(setCategories); if (id) adminApi.list<any>('BlogPost').then((rows)=>{ const p=rows.find((x)=>x.id===id); if(p) setForm({...form,...p}); }); }, [id]);
  const save = async () => { const slug = form.slug || form.title.replace(/\s+/g,'-'); if (isEditing) await adminApi.update('BlogPost', id!, { ...form, slug }); else await adminApi.create('BlogPost', { ...form, slug }); router.push('/admin/blog'); };
  return <div className="p-6 sm:p-8 max-w-6xl" dir="rtl"><div className="flex items-center justify-between mb-6"><h1 className="text-xl font-extrabold">{isEditing?'ویرایش مقاله':'مقاله جدید'}</h1><button onClick={save} className="px-4 py-2 rounded-lg bg-primary text-primary-foreground">ذخیره</button></div><div className="grid grid-cols-1 lg:grid-cols-5 gap-6"><div className="lg:col-span-3 space-y-4"><input className="w-full border rounded-lg px-3 py-2" placeholder="عنوان" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><textarea className="w-full border rounded-lg px-3 py-2 min-h-24" placeholder="خلاصه" value={form.excerpt} onChange={(e)=>setForm({...form,excerpt:e.target.value})}/><textarea className="w-full border rounded-lg px-3 py-2 min-h-72" placeholder="محتوا (HTML)" value={form.content} onChange={(e)=>setForm({...form,content:e.target.value})}/></div><div className="lg:col-span-2 space-y-4"><input className="w-full border rounded-lg px-3 py-2" placeholder="تصویر شاخص URL" value={form.cover_image} onChange={(e)=>setForm({...form,cover_image:e.target.value})}/><select className="w-full border rounded-lg px-3 py-2" value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})}><option value="">انتخاب دسته</option>{categories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select><div className="flex gap-2"><input className="w-full border rounded-lg px-3 py-2" value={tagInput} onChange={(e)=>setTagInput(e.target.value)} placeholder="برچسب"/><button onClick={()=>{if(tagInput.trim()) {setForm({...form,tags:[...form.tags, tagInput.trim()]});setTagInput('');}}} className="px-3 rounded bg-secondary">+</button></div><div className="flex flex-wrap gap-2">{form.tags.map((t:string)=><button key={t} onClick={()=>setForm({...form,tags:form.tags.filter((x:string)=>x!==t)})} className="px-2 py-1 bg-secondary rounded-full text-xs">{t} ×</button>)}</div>{isEditing && id ? <SeoTab entity={form} entityType='blog_post' entityId={id} /> : <div className='rounded border p-3 text-sm text-muted-foreground'>پس از ذخیره مقاله، پنل SEO فعال می‌شود.</div>}</div></div></div>;
}
