'use client';
import Link from 'next/link';

export default function BlogSidebar({ categories = [], recentPosts = [], tags = [], searchQuery, onSearchChange, selectedCategory, onCategoryChange }: any) {
  return <div className="space-y-6" dir="rtl">
    <div className="bg-card rounded-2xl border border-border/60 p-5"><h3 className="font-bold text-base mb-3 flex items-center gap-2">⌕جستجو</h3><input placeholder="جستجو در مقالات..." value={searchQuery} onChange={(e)=>onSearchChange(e.target.value)} className="w-full pr-4 text-sm bg-secondary/50 border border-border/40 rounded-lg py-2"/></div>
    <div className="bg-card rounded-2xl border border-border/60 p-5"><h3 className="font-bold text-base mb-3 flex items-center gap-2">🗂دسته‌بندی‌ها</h3><div className="space-y-1"><button onClick={()=>onCategoryChange(null)} className={`w-full text-right px-3 py-2 rounded-lg text-sm ${!selectedCategory?'bg-primary text-primary-foreground':'hover:bg-secondary'}`}>همه مقالات</button>{categories.map((cat:any)=><button key={cat.id} onClick={()=>onCategoryChange(cat.name)} className={`w-full text-right px-3 py-2 rounded-lg text-sm ${selectedCategory===cat.name?'bg-primary text-primary-foreground':'hover:bg-secondary'}`}>{cat.name}</button>)}</div></div>
    <div className="bg-card rounded-2xl border border-border/60 p-5"><h3 className="font-bold text-base mb-3 flex items-center gap-2">↗محبوب‌ترین‌ها</h3><div className="space-y-3">{recentPosts.map((post:any,i:number)=><Link key={post.id} href={`/blog/${post.slug}`} className="flex items-start gap-3 group"><span className="w-7 h-7 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">{i+1}</span><span className="text-sm leading-relaxed group-hover:text-primary line-clamp-2">{post.title}</span></Link>)}</div></div>
    <div className="bg-card rounded-2xl border border-border/60 p-5"><h3 className="font-bold text-base mb-3 flex items-center gap-2">🏷برچسب‌ها</h3><div className="flex flex-wrap gap-2">{tags.map((tag:string)=><span key={tag} className="cursor-pointer hover:bg-primary hover:text-primary-foreground transition-colors text-xs px-2 py-1 rounded-full bg-secondary">{tag}</span>)}</div></div>
  </div>;
}
